export const resumeData = {
  name: 'Mondira Chanda',
  title: 'Frontend Developer',
  tagline: 'Crafting pixel-perfect experiences with React, Next.js & TypeScript',
  status: 'Immediate Joiner',
  contact: {
    email: 'mondirachanda7@gmail.com',
    phone: '+91 7318930111',
    location: 'Asansol, West Bengal',
    linkedin: 'https://linkedin.com/in/mondira-chanda-50214b264',
    github: 'https://github.com/mondira07',
  },
  about: `Frontend Developer with hands-on experience building high-performance, scalable web applications using React.js, Next.js, and TypeScript. Specialized in transforming Figma designs into pixel-perfect, accessible components, optimizing performance through code splitting and memoization, and integrating real-time data with RESTful APIs and WebSockets. Passionate about clean architecture, reusable component libraries, and delivering experiences that increase user engagement.`,
  experience: [
    {
      company: 'Anotech India Solutions',
      role: 'Frontend Developer — Upraise (LMS)',
      dates: 'Sep 2025 — Present',
      location: 'Asansol, West Bengal',
      tag: 'Live',
      points: [
        'Developed Learning Management System using Next.js (SSR/SSG), TypeScript, and Tailwind CSS with responsive design.',
        'Built reusable component library with custom hooks and optimized rendering using React.memo and useMemo.',
        'Established Git workflows and automated deployment via GitHub Actions for continuous integration.',
        'Transformed Figma mockups into pixel-perfect, accessible components following design system standards.',
        'Optimized performance through code splitting, lazy loading, and dynamic imports — reducing load time by 30%.',
        'Integrated RESTful APIs with error handling and implemented caching strategies for improved data fetching.',
      ],
    },
    {
      company: 'Anotech India Solutions',
      role: 'Frontend Developer — Skill-based Gaming Platform',
      dates: 'Mar 2025 — Sep 2025',
      location: 'Asansol, West Bengal',
      tag: 'Shipped',
      points: [
        'Delivered 8+ responsive themes using React.js, TypeScript, and Material UI with modular, scalable architecture.',
        'Implemented Redux Toolkit for global state and React Query for server-state with caching and invalidation.',
        'Integrated RESTful APIs and WebSocket for real-time updates, notifications, and synchronized dashboards.',
        'Built custom React hooks and optimized re-renders using useCallback, useMemo, and virtualization techniques.',
        'Achieved 15% increase in user engagement and generated $20K revenue through performance improvements.',
        'Conducted code reviews, enforced TypeScript best practices, and mentored junior developers on React patterns.',
      ],
    },
    {
      company: 'Anotech India Solutions',
      role: 'Frontend Developer — Digital Asset Investment Platform',
      dates: 'Jan 2025 — Mar 2025',
      location: 'Asansol, West Bengal',
      tag: 'Live',
      points: [
        'Built real-time dashboard with React.js, TypeScript, and Material UI for portfolio monitoring and analytics.',
        'Engineered secure authentication flow with JWT tokens, session management, and protected routes.',
        'Designed interactive data visualizations using chart libraries with optimized rendering for large datasets.',
        'Implemented responsive, mobile-first design with CSS Grid and Flexbox ensuring cross-browser compatibility.',
        'Optimized API calls with debouncing, caching, and request batching to reduce server load.',
        'Applied error boundaries, loading states, and retry logic for robust user experience.',
      ],
    },
  ],
  education: [
    { school: 'Asansol Engineering College', degree: "Bachelor's in Computer Application", date: '2024', score: '8.14 CGPA' },
    { school: 'Santinagar Vidyamandir', degree: 'Class XII (Board)', date: '2021', score: '72%' },
  ],
  skills: {
    Languages: ['JavaScript (ES6+)', 'TypeScript', 'HTML5', 'CSS3'],
    Frameworks: ['React.js', 'Next.js', 'Node.js', 'Express.js', 'Tailwind CSS', 'Material UI'],
    'State & Data': ['Redux Toolkit', 'Context API', 'React Query', 'Custom Hooks'],
    Optimization: ['Code Splitting', 'Lazy Loading', 'Memoization', 'Debouncing', 'Caching'],
    'Tools & Others': ['Git', 'GitHub Actions', 'MongoDB', 'JWT Auth', 'RESTful APIs', 'WebSocket', 'Figma'],
  },
  projects: [
    {
      name: 'StudyNotion — EdTech Learning Platform',
      stack: ['MERN', 'Tailwind CSS', 'Razorpay', 'Redux Toolkit', 'JWT'],
      points: [
        'Full-stack EdTech platform built on MERN with Tailwind CSS and Razorpay payment gateway.',
        'RESTful APIs with JWT authentication, bcrypt hashing, and Role-Based Access Control.',
        'React Router with code splitting + lazy loading achieving a 95+ Lighthouse score.',
        'Optimized bundle via tree shaking, dynamic imports, and image optimization.',
      ],
      link: '#',
    },
    {
      name: 'AlgoDesk — Spreadsheet Visualizer',
      stack: ['React', 'DFS', 'Virtualization', 'CSV/JSON'],
      points: [
        'High-performance spreadsheet with list virtualization handling 10,000+ cells smoothly.',
        'DFS algorithm for cycle detection and formula dependency resolution with memoization.',
        'Event delegation, debounced inputs, and requestAnimationFrame for smooth scrolling.',
        'Graph-based cell dependency system with incremental updates to minimize re-renders.',
      ],
      link: 'https://github.com/mondira07',
    },
  ],
};